--Q1: Find the top 3 selling cities of each country.

WITH CitySales AS (
    SELECT L.Country, L.City, SUM(F.Sales) AS TotalSales
    FROM Fact F
    JOIN Location L ON F.[Location ID] = L.[Location ID]
    GROUP BY L.Country, L.City
)
SELECT Country, City, TotalSales
FROM (
    SELECT Country, City, TotalSales, 
           RANK() OVER (PARTITION BY Country ORDER BY TotalSales DESC) AS Rank
    FROM CitySales
) AS RankedCities
WHERE Rank <= 3;

select L.Country, L.City, SUM(F.Sales) as 'c1', DENSE_RANK() over(PARTITION by L.Country order by [Total Sales] desc)
from Fact F left join Location L on F.[Location ID]=L.[Location ID]
group by L.Country,L.City


--Q2: Find year-over-year percentage growth in sales.

SELECT YEAR(F.[Order Date]) AS Year,
       SUM(F.Sales) AS TotalSales,
       COALESCE(
           (SUM(F.Sales) - LAG(SUM(F.Sales)) OVER (ORDER BY YEAR(F.OrderDate))) * 100.0 / LAG(SUM(F.Sales)) OVER (ORDER BY YEAR(F.OrderDate)),
           0
       ) AS SalesGrowthPercentage
FROM Fact F
GROUP BY YEAR(F.[Order Date]);

--Q3: Find average city sales for each country.

SELECT L.Country, L.City, AVG(F.Sales) AS AvgCitySales
FROM Fact F
JOIN Location L ON F.[Location ID] = L.[Location ID]
GROUP BY L.Country, L.City;

--Q4: Find the number of countries where at least 5 cities have made sales more than 10000.
WITH CitySales AS(
    SELECT 
        L.Country, 
        L.City, 
        SUM(F.Sales) AS TotalSales
    FROM Fact F
    JOIN Location L ON F.[Location ID] = L.[Location ID]
    GROUP BY L.Country, L.City
),
CountryCityCount AS (
    SELECT 
        Country, 
        COUNT(City) AS CitiesWithSalesAbove10000
    FROM CitySales
    WHERE TotalSales > 10000
    GROUP BY Country
)
SELECT COUNT(Country) AS CountryCount
FROM CountryCityCount
WHERE CitiesWithSalesAbove10000 >= 5;



--Q5: Find the average order value of each customer.

SELECT F.[Customer ID], AVG(F.Sales) AS AvgOrderValue
FROM Fact F
GROUP BY F.[Customer ID]
ORDER BY AvgOrderValue

--Q6: Find the number of Indian customers who have produced an overall loss.
SELECT 
    COUNT(DISTINCT F.[Customer ID]) AS IndianCustomersWithLoss
FROM Fact F
JOIN Customer C ON F.[Customer ID] = C.[Customer ID]
JOIN Location L ON F.[Location ID] = L.[Location ID]
WHERE L.Country = 'India'
  AND F.Profit < 0;


--Q7: Find the top-selling sub-category in each segment.

SELECT C.Segment, P.[Sub-Category], SUM(F.Sales) AS TotalSales
FROM Fact F
JOIN Product P ON F.[Product ID] = P.[Product ID]
JOIN Customer C ON F.[Customer ID] = C.[Customer ID]
GROUP BY C.Segment, P.[Sub-Category]
ORDER BY C.Segment, P.[Sub-Category], TotalSales

--Q8: Find the quarter-over-quarter sales in India.

WITH QuarterlySales AS (
    SELECT 
        YEAR(F.[Order Date]) AS SalesYear,
        DATEPART(QUARTER, F.[Order Date]) AS SalesQuarter,
        SUM(F.Sales) AS TotalSales
    FROM Fact F
    JOIN Location L ON F.[Location ID] = L.[Location ID]
    WHERE L.Country = 'India'
    GROUP BY YEAR(F.[Order Date]), DATEPART(QUARTER, F.[Order Date])
),
QuarterlyGrowth AS (
    SELECT 
        SalesYear,
        SalesQuarter,
        TotalSales,
        LAG(TotalSales) OVER (ORDER BY SalesYear, SalesQuarter) AS PreviousQuarterSales
    FROM QuarterlySales
)
SELECT 
    SalesYear,
    SalesQuarter,
    TotalSales,
    (TotalSales - PreviousQuarterSales) * 100.0 / PreviousQuarterSales AS QoQGrowthPercentage
FROM QuarterlyGrowth


--Q9: Find the top 10 selling products in the current quarter.

WITH cte AS(
	SELECT P.[Product Name], SUM(F.Sales) [Total Sales], DENSE_RANK() OVER(ORDER BY SUM(F.Sales) DESC) rk
	FROM Fact F JOIN Product P ON F.[Product ID] = P.[Product ID]
	WHERE DATEPART(QUARTER, [Order Date]) = DATEPART(QUARTER, GETDATE())
	GROUP BY P.[Product Name]
)
SELECT [Product Name], [Total Sales]
FROM cte
WHERE rk <=10
ORDER BY [Total Sales] DESC


--Q10: Show segment-wise average profit per order.

SELECT 
    C.Segment, 
    AVG(F.Profit) AS AverageProfitPerOrder
FROM 
    Fact F
    JOIN Customer C ON F.[Customer ID] = C.[Customer ID]
GROUP BY 
    C.Segment
ORDER BY 
    C.Segment


--Q11: Find the percent profit generated by each sub-category.
SELECT 
    P.[Sub-Category], 
    SUM(F.Profit) AS TotalProfit,
    (SUM(F.Profit) * 100.0 / (SELECT SUM(Profit) FROM Fact)) AS PercentProfit
FROM 
    Fact F
    JOIN Product P ON F.[Product ID] = P.[Product ID]
GROUP BY 
    P.[Sub-Category]
ORDER BY 
    PercentProfit DESC


--Q12: Find the list of 10 customers in a single output, 5 customers generating maximum profits, and 5 customers generating maximum losses.

WITH TopProfitableCustomers AS (
    SELECT TOP 5
        C.[Customer ID], 
        C.[Customer Name], 
        SUM(F.Profit) AS TotalProfit
    FROM 
        Fact F
        JOIN Customer C ON F.[Customer ID] = C.[Customer ID]
    GROUP BY 
        C.[Customer ID], C.[Customer Name]
    ORDER BY 
        TotalProfit DESC
),
TopLossCustomers AS (
    SELECT TOP 5
        C.[Customer ID], 
        C.[Customer Name], 
        SUM(F.Profit) AS TotalProfit
    FROM 
        Fact F
        JOIN Customer C ON F.[Customer ID] = C.[Customer ID]
    GROUP BY 
        C.[Customer ID], C.[Customer Name]
    ORDER BY 
        TotalProfit ASC
)
SELECT * FROM TopProfitableCustomers
UNION ALL
SELECT * FROM TopLossCustomers







--Q13: Find the most profitable combination of Category and Segment, based on percent profit.
SELECT TOP 1 
    p.Category, 
    c.Segment, 
    SUM(f.Profit) / (SELECT SUM(Profit) FROM Fact) * 100 AS PercentProfit
FROM 
    Fact f 
    LEFT JOIN Product p ON f.[Product ID] = p.[Product ID] 
    LEFT JOIN Customer c ON f.[Customer ID] = c.[Customer ID]
GROUP BY 
    p.Category, c.Segment
ORDER BY 
    PercentProfit DESC


--Q14: Find the list of customers who have not placed orders in the last 100 days.

SELECT 
    C.[Customer ID],
    C.[Customer Name]
FROM Customer C
WHERE NOT EXISTS (
    SELECT *
    FROM Fact F
    WHERE F.[Customer ID] = C.[Customer ID]
    AND F.[Order Date] > DATEDIFF(DAY, 100, GETDATE())
)

SELECT 
    C.[Customer ID],
    C.[Customer Name]
FROM Customer C
LEFT JOIN Fact F ON C.[Customer ID] = F.[Customer ID] 
    AND F.[Order Date] > DATEADD(DAY, -100, GETDATE())
WHERE F.[Customer ID] IS NULL;


--Q15: Find the list of customers who placed only one order till now.

SELECT F.[Customer ID]
FROM Fact F
GROUP BY F.[Customer ID]
HAVING COUNT(F.[Order ID]) = 1;

--Q16: Find the most popular product in each state of India, based on Quantity sold.

WITH ProductSales AS (
    SELECT 
        L.State, 
        P.[Product Name],
        DENSE_RANK() OVER (PARTITION BY State ORDER BY SUM(F.Quantity) DESC) AS ProductRank
    FROM 
        Fact F
        JOIN Product P ON F.[Product ID] = P.[Product ID]
        JOIN Location L ON F.[Location ID] = L.[Location ID]
    WHERE 
        L.Country = 'India'
    GROUP BY 
        L.State, P.[Product Name]
)
SELECT State, [Product Name]
FROM ProductSales
WHERE ProductRank = 1


--Q17: Find the first and the last order date for each customer, and also calculate the number of days between the two dates.

SELECT
	[Customer ID], 
    MIN([Order Date]) AS FirstOrderDate, 
    MAX([Order Date]) AS LastOrderDate,
    DATEDIFF(DAY, MIN([Order Date]), MAX([Order Date])) AS DaysBetween
FROM 
	Fact
GROUP BY
	[Customer ID]


--Q18: Find the monthly sales for the last 10 months, including the ongoing month.

SELECT YEAR(F.[Order Date]) AS Year, 
       MONTH(F.[Order Date]) AS Month, 
       SUM(F.Sales) AS TotalSales
FROM Fact F
WHERE F.[Order Date] >= DATEDIFF(MONTH, 10, GETDATE())
GROUP BY YEAR(F.[Order Date]), MONTH(F.[Order Date])
ORDER BY Year, Month ASC

--Q19: Find the average selling price of each product.


SELECT P.[Product Name], AVG(F.Sales / F.Quantity) AS AvgSellingPrice
FROM Fact F
JOIN Product P ON F.[Product ID] = P.[Product ID]
GROUP BY P.[Product Name]
ORDER BY AvgSellingPrice DESC

--Q20: Find the average number of days taken to ship products for each country.
SELECT 
    L.Country, 
    AVG(DATEDIFF(DAY, F.[Order Date], F.[Ship Date])) AS AverageShippingDays
FROM 
    Fact F
    JOIN Location L ON F.[Location ID] = L.[Location ID]
GROUP BY 
    L.Country
ORDER BY 
    AverageShippingDays ASC;

